/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vidulaPharma.view.admin;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxEditor;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import vidulaPharma.controller.PharmaNameController;
import vidulaPharma.controller.TradeNameController;
import vidulaPharma.etc.IdGen;
import vidulaPharma.model.PharamaName;
import vidulaPharma.model.TradeName;

/**
 *
 * @author isuru
 */
public class AddNewBrand extends javax.swing.JInternalFrame {

    private AddItemFrame parent;
    private static AddNewBrand addNewBrand;
    private ComboBoxModel<PharamaName> comboModel;
    /**
     * Creates new form AddNewBrand
     */
//    public AddNewBrand() {
//        initComponents();
//    }
    
    private AddNewBrand(AddItemFrame parent) {
        initComponents();
        this.parent = parent;
        try {
            this.parent.setIcon(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AddNewBrand.class.getName()).log(Level.SEVERE, null, ex);
        }
        optButtonGroup.add(optButtonExisting);
        optButtonGroup.add(optButtonNew);
        optButtonGroup.setSelected(optButtonNew.getModel(), true);
        toggleExistingPanel(false);
        togglePanelNew(true);
        comboModel = existingGenericCombo.getModel();
        setCombo();
    }
    
    public static AddNewBrand getInstance(AddItemFrame parent){
        if(AddNewBrand.addNewBrand == null){
            addNewBrand = new AddNewBrand(parent);
        }
        return addNewBrand;
    }
    
    private void togglePanelNew(boolean state){
        panelNew.setEnabled(state);
        newGenericText.setEnabled(state);
    }
    
    private void toggleExistingPanel(boolean state){
        panelExisting.setEnabled(state);
        existingGenericCombo.setEnabled(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optButtonGroup = new javax.swing.ButtonGroup();
        brandLabel = new javax.swing.JLabel();
        brandText = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        optButtonNew = new javax.swing.JRadioButton();
        optButtonExisting = new javax.swing.JRadioButton();
        panelNew = new javax.swing.JPanel();
        newGenericText = new javax.swing.JTextField();
        panelExisting = new javax.swing.JPanel();
        existingGenericCombo = new javax.swing.JComboBox();

        setTitle("Add New Brand");
        setFocusable(false);
        setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        brandLabel.setText("Brand");

        brandText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTextActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Generic Name"));

        optButtonNew.setText("New");
        optButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optButtonNewActionPerformed(evt);
            }
        });

        optButtonExisting.setText("Existing");
        optButtonExisting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optButtonExistingActionPerformed(evt);
            }
        });

        panelNew.setBorder(javax.swing.BorderFactory.createTitledBorder("New"));
        panelNew.setEnabled(false);

        newGenericText.setText("New Generic Name");

        javax.swing.GroupLayout panelNewLayout = new javax.swing.GroupLayout(panelNew);
        panelNew.setLayout(panelNewLayout);
        panelNewLayout.setHorizontalGroup(
            panelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newGenericText, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNewLayout.setVerticalGroup(
            panelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newGenericText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelExisting.setBorder(javax.swing.BorderFactory.createTitledBorder("Existing"));
        panelExisting.setEnabled(false);

        existingGenericCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Generic Name" }));

        javax.swing.GroupLayout panelExistingLayout = new javax.swing.GroupLayout(panelExisting);
        panelExisting.setLayout(panelExistingLayout);
        panelExistingLayout.setHorizontalGroup(
            panelExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExistingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(existingGenericCombo, 0, 349, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelExistingLayout.setVerticalGroup(
            panelExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExistingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(existingGenericCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(panelNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelExisting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(optButtonNew)
                        .addGap(18, 18, 18)
                        .addComponent(optButtonExisting)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optButtonNew)
                    .addComponent(optButtonExisting))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelNew, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelExisting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brandLabel)
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brandText))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLabel)
                    .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        try {
            // TODO add your handling code here:
            this.parent.setIcon(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AddNewBrand.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.doDefaultCloseAction();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void optButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optButtonNewActionPerformed
        togglePanelNew(true);
        newGenericText.requestFocus();
        toggleExistingPanel(false);
    }//GEN-LAST:event_optButtonNewActionPerformed

    private void optButtonExistingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optButtonExistingActionPerformed
        toggleExistingPanel(true);
        existingGenericCombo.requestFocus();
        togglePanelNew(false);
    }//GEN-LAST:event_optButtonExistingActionPerformed

    private void setCombo(){
        ArrayList<PharamaName> nameList = null;
        try {
            nameList = (ArrayList<PharamaName>) PharmaNameController.getAll();
        } catch (SQLException ex) {
            Logger.getLogger(AddNewBrand.class.getName()).log(Level.SEVERE, null, ex);
        }
        existingGenericCombo.setModel(comboModel);
        for(PharamaName pName : nameList){
            existingGenericCombo.addItem(pName);
        }
    }
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            TradeName brandName;
            PharamaName genericName = null;
            String pharmaId = null;
            boolean addPharmaName=false;
            
            if(optButtonNew.isSelected()){
                pharmaId = PharmaNameController.getNewId();
               genericName = new PharamaName(pharmaId, newGenericText.getText());
               addPharmaName = PharmaNameController.addPharmaName(genericName);
            }else if(optButtonExisting.isSelected()){
                genericName = (PharamaName) existingGenericCombo.getSelectedItem();
                pharmaId = genericName.getPharmaId();
                addPharmaName = true;
            }
            
            if(addPharmaName){
                String brandId = TradeNameController.getNewId();
                //System.out.println(brandId+"--"+pharmaId);
                String strBrandName = brandText.getText();
                TradeName newBrand = new TradeName(brandId, pharmaId, strBrandName);
                boolean addBrandName = TradeNameController.addPharmaName(newBrand);
                if(addBrandName){
                    JOptionPane.showInternalMessageDialog(AddNewBrand.this, "Successfully Added", "Success", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showInternalMessageDialog(AddNewBrand.this, "ERROR : CANNOT ADD BRAND NAME", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showInternalMessageDialog(AddNewBrand.this, "ERROR : CANNOT SET GENERIC NAME", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddNewBrand.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void brandTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTextActionPerformed
            optButtonNew.requestFocus();
    }//GEN-LAST:event_brandTextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandLabel;
    private javax.swing.JTextField brandText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox existingGenericCombo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField newGenericText;
    private javax.swing.JRadioButton optButtonExisting;
    private javax.swing.ButtonGroup optButtonGroup;
    private javax.swing.JRadioButton optButtonNew;
    private javax.swing.JPanel panelExisting;
    private javax.swing.JPanel panelNew;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
