/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vidulaPharma.view.admin;

import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author isuru
 */
public class AdminMainForm extends javax.swing.JFrame {

    private static AdminMainForm admin;
    ImageIcon icon;
    private Timer currentTime;
    // AddEmployeeForm addEmployeeForm;

    /**
     * Creates new form AdminMainForm
     */
    public AdminMainForm() {
        admin = AdminMainForm.this;
        initComponents();
        setExtendedState(Frame.MAXIMIZED_BOTH);
        dateLabel.setText(new SimpleDateFormat("EEEE    dd - mm - yyyy").format(new Date()));
        currentTime = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timeLabel.setText(new SimpleDateFormat("hh:mm:ss a").format(new Date()));
            }
        });
        currentTime.start();
        //mainDeskPane.setUI(null);
    }

    protected static AdminMainForm getInstance(){
        return admin;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addOrderButton = new javax.swing.JButton();
        outdatedButton = new javax.swing.JButton();
        outOfStockButton = new javax.swing.JButton();
        paymentsButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        mainDeskPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenuItem();
        drugMenu = new javax.swing.JMenu();
        searchDrugMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        addEmployee = new javax.swing.JMenuItem();
        searchEmployeeMenu = new javax.swing.JMenuItem();
        supplierMenu = new javax.swing.JMenu();
        addSupplierMenuItem = new javax.swing.JMenuItem();
        searchSupplierMenu = new javax.swing.JMenuItem();
        ordersMenu = new javax.swing.JMenu();
        reciveOrderMenuItem = new javax.swing.JMenuItem();
        viewOrdersMenuItem = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        helpMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vidula Pharma");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        addOrderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidulaPharma/images/Document-Add-icon.png"))); // NOI18N
        addOrderButton.setText("Add Order");
        addOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderButtonActionPerformed(evt);
            }
        });

        outdatedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidulaPharma/images/history.png"))); // NOI18N
        outdatedButton.setText("Expires");
        outdatedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outdatedButtonActionPerformed(evt);
            }
        });

        outOfStockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidulaPharma/images/empty.png"))); // NOI18N
        outOfStockButton.setText("Low Stock");
        outOfStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outOfStockButtonActionPerformed(evt);
            }
        });

        paymentsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidulaPharma/images/512_icon.png"))); // NOI18N
        paymentsButton.setText("Payments");
        paymentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsButtonActionPerformed(evt);
            }
        });

        addItemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidulaPharma/images/Packet-add-icon.png"))); // NOI18N
        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        dateLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("Date");

        timeLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addItemButton)
                .addGap(18, 18, 18)
                .addComponent(addOrderButton)
                .addGap(21, 21, 21)
                .addComponent(outdatedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outOfStockButton)
                .addGap(18, 18, 18)
                .addComponent(paymentsButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addItemButton)
                            .addComponent(outdatedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outOfStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paymentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(timeLabel)
                        .addGap(31, 31, 31))))
        );

        mainDeskPane.setBackground(new java.awt.Color(118, 114, 109));
        mainDeskPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        fileMenu.setText("File");

        exitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenu.setText("Exit");
        fileMenu.add(exitMenu);

        jMenuBar1.add(fileMenu);

        drugMenu.setText("Drug");

        searchDrugMenu.setText("Search");
        drugMenu.add(searchDrugMenu);

        jMenuBar1.add(drugMenu);

        jMenu3.setText("Employee");

        addEmployee.setText("Add Employee");
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });
        jMenu3.add(addEmployee);

        searchEmployeeMenu.setText("Search");
        searchEmployeeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmployeeMenuActionPerformed(evt);
            }
        });
        jMenu3.add(searchEmployeeMenu);

        jMenuBar1.add(jMenu3);

        supplierMenu.setText("Supplier");

        addSupplierMenuItem.setText("Add Supplier");
        addSupplierMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierMenuItemActionPerformed(evt);
            }
        });
        supplierMenu.add(addSupplierMenuItem);

        searchSupplierMenu.setText("Search Supplier");
        searchSupplierMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSupplierMenuActionPerformed(evt);
            }
        });
        supplierMenu.add(searchSupplierMenu);

        jMenuBar1.add(supplierMenu);

        ordersMenu.setText("Orders");

        reciveOrderMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        reciveOrderMenuItem.setText("Receive Order");
        ordersMenu.add(reciveOrderMenuItem);

        viewOrdersMenuItem.setText("View Orders");
        viewOrdersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersMenuItemActionPerformed(evt);
            }
        });
        ordersMenu.add(viewOrdersMenuItem);

        jMenuBar1.add(ordersMenu);

        aboutMenu.setText("About");

        aboutMenuItem.setText("About");
        aboutMenu.add(aboutMenuItem);

        helpMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        helpMenuItem.setText("Help");
        aboutMenu.add(helpMenuItem);

        jMenuBar1.add(aboutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainDeskPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainDeskPane, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addComponent(Component component) {
        this.mainDeskPane.add(component);
    }
    private void addOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderButtonActionPerformed
        mainDeskPane.removeAll();
        mainDeskPane.repaint();
        AddOrderForm addOrderForm = AddOrderForm.getInstance();
        showForm(addOrderForm);
    }//GEN-LAST:event_addOrderButtonActionPerformed
    
    protected void showForm(JInternalFrame frame){
        if (!frame.isShowing()) {
            mainDeskPane.add(frame);
            frame.setVisible(true);
            try {
                frame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                frame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
        mainDeskPane.removeAll();
        mainDeskPane.repaint();
        AddItemFrame addItemFrame = AddItemFrame.getInstance(AdminMainForm.this);
        if (!addItemFrame.isShowing()) {
            mainDeskPane.add(addItemFrame);
            addItemFrame.setVisible(true);
        } else {
            try {
                addItemFrame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_addItemButtonActionPerformed

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        // TODO add your handling code here:
        mainDeskPane.removeAll();
        mainDeskPane.repaint();
        AddEmployeeFrame frame = AddEmployeeFrame.getInstance();
        if (!frame.isShowing()) {
            mainDeskPane.add(frame);
            frame.setVisible(true);
        } else {
            try {
                frame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //addEmployee.setEnabled(false);
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void addSupplierMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierMenuItemActionPerformed
        // TODO add your handling code here:
        mainDeskPane.removeAll();
        mainDeskPane.repaint();
        AddSupplierFrame addSupplierFrame = AddSupplierFrame.getInstance();
        if (!addSupplierFrame.isShowing()) {
            mainDeskPane.add(addSupplierFrame);
            addSupplierFrame.setVisible(true);
        } else {
            try {
                addSupplierFrame.setSelected(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(AdminMainForm.this, "Error Loading Supplier Form");
            }
        }
    }//GEN-LAST:event_addSupplierMenuItemActionPerformed

    private void outdatedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outdatedButtonActionPerformed
        // TODO add your handling code here:
        mainDeskPane.removeAll();
        mainDeskPane.repaint();
        ViewExpiredItema viewExpiredItems = ViewExpiredItema.getInstance();
        if (!viewExpiredItems.isShowing()) {
            mainDeskPane.add(viewExpiredItems);
            viewExpiredItems.setVisible(true);
        } else {
            try {
                viewExpiredItems.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_outdatedButtonActionPerformed

    private void searchSupplierMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSupplierMenuActionPerformed
        // TODO add your handling code here:
        mainDeskPane.removeAll();
        mainDeskPane.repaint();
        SearchSupplierForm searchSupplierForm;
        searchSupplierForm = SearchSupplierForm.getInstance();
        if (!searchSupplierForm.isShowing()) {
            mainDeskPane.add(searchSupplierForm);
            searchSupplierForm.setVisible(true);
        } else {
            try {
                searchSupplierForm.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_searchSupplierMenuActionPerformed

    private void searchEmployeeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmployeeMenuActionPerformed
        mainDeskPane.removeAll();
        mainDeskPane.repaint();
        EmployeeSearchForm searchEmployeeForm;
        searchEmployeeForm = EmployeeSearchForm.getInstance();
        if (!searchEmployeeForm.isShowing()) {
            mainDeskPane.add(searchEmployeeForm);
            searchEmployeeForm.setVisible(true);
        } else {
            try {
                searchEmployeeForm.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchEmployeeMenuActionPerformed

    private void paymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsButtonActionPerformed
        mainDeskPane.removeAll();
        mainDeskPane.repaint();
        ViewPaymentsForm viewPayments = ViewPaymentsForm.getInstance();
        if (!viewPayments.isShowing()) {
            mainDeskPane.add(viewPayments);
            viewPayments.setVisible(true);
        } else {
            try {
                viewPayments.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_paymentsButtonActionPerformed

    private void outOfStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outOfStockButtonActionPerformed
        mainDeskPane.removeAll();
        mainDeskPane.repaint();
        ViewLowStockForm lowStockForm = ViewLowStockForm.getInstance();
        if (!lowStockForm.isShowing()) {
            mainDeskPane.add(lowStockForm);
            lowStockForm.setVisible(true);
//            try {
//                lowStockForm.setMaximum(true);
//            } catch (PropertyVetoException ex) {
//                Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
        } else {
            try {
                lowStockForm.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AdminMainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    // TODO add your handling code here:
    }//GEN-LAST:event_outOfStockButtonActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        //
    }//GEN-LAST:event_formKeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void viewOrdersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersMenuItemActionPerformed
        ViewOrdersForm viewOrdersForm = ViewOrdersForm.getInstance();
        showForm(viewOrdersForm);// TODO add your handling code here:
    }//GEN-LAST:event_viewOrdersMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        //set a custom look and feel        

        try {
            UIManager.setLookAndFeel(new AcrylLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminMainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem addEmployee;
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton addOrderButton;
    private javax.swing.JMenuItem addSupplierMenuItem;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JMenu drugMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane mainDeskPane;
    private javax.swing.JMenu ordersMenu;
    private javax.swing.JButton outOfStockButton;
    private javax.swing.JButton outdatedButton;
    private javax.swing.JButton paymentsButton;
    private javax.swing.JMenuItem reciveOrderMenuItem;
    private javax.swing.JMenuItem searchDrugMenu;
    private javax.swing.JMenuItem searchEmployeeMenu;
    private javax.swing.JMenuItem searchSupplierMenu;
    private javax.swing.JMenu supplierMenu;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JMenuItem viewOrdersMenuItem;
    // End of variables declaration//GEN-END:variables
}
