/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vidulaPharma.view.admin;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import vidulaPharma.controller.TradeNameController;
import vidulaPharma.model.SupplierOrderDetail;

/**
 *
 * @author isuru
 */
public class OrderDetailsForm extends javax.swing.JInternalFrame {
    private static OrderDetailsForm orderDetailsForm;
    /**
     * Creates new form OrderDetailsForm
     */
    private OrderDetailsForm() {
        initComponents();
    }

    public static OrderDetailsForm getInstance(){
        if(orderDetailsForm == null){
            orderDetailsForm = new OrderDetailsForm();
        }
        return orderDetailsForm;
    }
    
    protected void setTabel(ArrayList<SupplierOrderDetail> detailList){
        DefaultTableModel dtModel = (DefaultTableModel) detailTable.getModel();
        dtModel.setRowCount(0);
        for(SupplierOrderDetail sOrderDetail : detailList){
            Object[] rowData = null;
            try {
                rowData = new Object[]{TradeNameController.searchTradeId(sOrderDetail.getDrugId()),sOrderDetail.getDose(),sOrderDetail.getUnitType(),sOrderDetail.getQty()};
            } catch (SQLException ex) {
                Logger.getLogger(OrderDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            dtModel.addRow(rowData);
        }
        detailTable.setModel(dtModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();
        okButton = new javax.swing.JButton();

        setTitle("Order Details");

        detailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Trade Name", "Dose", "Type", "Qty"
            }
        ));
        jScrollPane1.setViewportView(detailTable);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
            .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detailTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
