/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vidulaPharma.view.admin;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vidulaPharma.controller.DrugController;
import vidulaPharma.controller.SupplierController;
import vidulaPharma.controller.SupplierOrderController;
import vidulaPharma.controller.SupplierOrderDetailController;
import vidulaPharma.controller.SupplierPaymentController;
import vidulaPharma.model.Drug;
import vidulaPharma.model.Supplier;
import vidulaPharma.model.SupplierOrder;
import vidulaPharma.model.SupplierOrderDetail;
import vidulaPharma.model.SupplierPayment;

/**
 *
 * @author isuru
 */
public class ViewOrdersForm extends javax.swing.JInternalFrame {

    private static ViewOrdersForm viewOrdersForm;
    private String date;
    private List<SupplierOrder> orderList;
    private DefaultTableModel dtModel;
    private String amount;

    /**
     * Creates new form ViewOrdersForm
     */
    private ViewOrdersForm() {
        initComponents();
        orderList = null;
        setCombo();
        dtModel = (DefaultTableModel) jTable1.getModel();
        checkBoxGroup.add(dateCheckBox);
        checkBoxGroup.add(supplierCheckBox);
    }

    public static ViewOrdersForm getInstance() {
        if (viewOrdersForm == null) {
            viewOrdersForm = new ViewOrdersForm();
        }
        return viewOrdersForm;
    }

    private void setSelectios() {
        if (dateCheckBox.isSelected() || supplierCheckBox.isSelected()) {
            if (!dateCheckBox.isSelected()) {
                dateChooser.setEnabled(false);
                supplierCombo.setEnabled(true);
            } else if (!supplierCheckBox.isSelected()) {
                supplierCombo.setEnabled(false);
                dateChooser.setEnabled(true);
            } else {
                dateChooser.setEnabled(true);
                supplierCombo.setEnabled(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        checkBoxGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dateCheckBox = new javax.swing.JCheckBox();
        supplierCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        supplierCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JCalendar();
        cancelButton = new javax.swing.JButton();
        detailsButton = new javax.swing.JButton();
        receiveButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("View Orders");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("View Order By"));

        dateCheckBox.setText("Date");
        dateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateCheckBoxActionPerformed(evt);
            }
        });

        supplierCheckBox.setText("Supplier");
        supplierCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supplierCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierCheckBox)
                    .addComponent(dateCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order Id", "Supplier ", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Date/Supplier"));

        supplierCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Supplier" }));
        supplierCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Supplier");

        jLabel2.setText("Date");

        dateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(supplierCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(supplierCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        detailsButton.setText("View Details");
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });

        receiveButton.setText("Receive Order");
        receiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(receiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(detailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        dateChooser.setEnabled(false);
        supplierCombo.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void dateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateCheckBoxActionPerformed
        setSelectios();        // TODO add your handling code here:
    }//GEN-LAST:event_dateCheckBoxActionPerformed

    private void supplierCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierCheckBoxActionPerformed
        setSelectios();        // TODO add your handling code here:
    }//GEN-LAST:event_supplierCheckBoxActionPerformed

    private void dateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserPropertyChange
        try {
            System.out.println(dateChooser.getDate().toString());
            SimpleDateFormat sdformat = new SimpleDateFormat("dd/MM/yyyy");
            date = sdformat.format(dateChooser.getDate());
            orderList = SupplierOrderController.searchByDate(date);
            setTable(orderList);
        } catch (SQLException ex) {
            Logger.getLogger(ViewOrdersForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dateChooserPropertyChange

    private void setTable(List<SupplierOrder> orderList) {
        dtModel.setRowCount(0);
        for (SupplierOrder sOrder : orderList) {
            try {
                Supplier supplier = SupplierController.getSupplier(sOrder.getSupplierId());
                Object[] rowData = {sOrder.getSupplierOrderId(), supplier.getSupplierName(), sOrder.getSupplierOrderDate()};
                dtModel.addRow(rowData);
            } catch (SQLException ex) {
                Logger.getLogger(ViewOrdersForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jTable1.setModel(dtModel);
    }
    private void detailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsButtonActionPerformed
        try {
            SupplierOrder sOrder = orderList.get(jTable1.getSelectedRow());
            List<SupplierOrderDetail> orderDetails = SupplierOrderDetailController.getOrderDetails(sOrder.getSupplierOrderId());
            OrderDetailsForm odf = OrderDetailsForm.getInstance();
            odf.setTabel((ArrayList<SupplierOrderDetail>) orderDetails);
            AdminMainForm.getInstance().showForm(odf);
        } catch (SQLException ex) {
            Logger.getLogger(ViewOrdersForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_detailsButtonActionPerformed

    protected void setAmount(String amount){
        this.amount = amount;
    }
    
    private void setCombo() {
        try {
            List<Supplier> supList = SupplierController.getAll();
            for (Supplier supplier : supList) {
                supplierCombo.addItem(supplier);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewOrdersForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void supplierComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierComboActionPerformed
        if (supplierCombo.getSelectedIndex() > 0) {
            try {
                Supplier supplier = (Supplier) supplierCombo.getSelectedItem();
                orderList = SupplierOrderController.searchSupplierOrder(supplier.getSupplierId(), "orderId");
                setTable(orderList);
            } catch (SQLException ex) {
                Logger.getLogger(ViewOrdersForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_supplierComboActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void receiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveButtonActionPerformed
        try {
            SupplierOrder sOrder = orderList.get(jTable1.getSelectedRow());
            SupplierPayment payment = SupplierPaymentController.searchSupplierPayment(sOrder.getSupplierPaymentId());
            ReceivePaymentForm receivePaymentForm = new ReceivePaymentForm(new JFrame(), true, ViewOrdersForm.this);
            receivePaymentForm.setVisible(true);
            if(!amount.isEmpty()){
                double dAmount = Double.parseDouble(amount);
                payment.setAmount(dAmount);
                payment.setIsPaid(true);
                boolean isUpdated = SupplierPaymentController.updatePayment(payment);
                if(isUpdated){
                    List<SupplierOrderDetail> orderDetails = SupplierOrderDetailController.getOrderDetails(sOrder.getSupplierOrderId());
                    ArrayList<Drug> drugList = new ArrayList<>();
                    for(SupplierOrderDetail sOrderDetail : orderDetails){
                        Drug drug = DrugController.searchDrugByTradeName(sOrderDetail.getDrugId());
                        drug.setQtyOnHand(sOrderDetail.getQty());
                        drug.setAvailability(true);
                        drugList.add(drug);
                    }
                    for(Drug drug : drugList){
                        boolean drugUpdated = DrugController.updateDrug(drug);
                        JOptionPane.showInternalMessageDialog(ViewOrdersForm.this, drugUpdated);
                    }
                    
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewOrdersForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_receiveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.ButtonGroup checkBoxGroup;
    private javax.swing.JCheckBox dateCheckBox;
    private com.toedter.calendar.JCalendar dateChooser;
    private javax.swing.JButton detailsButton;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton receiveButton;
    private javax.swing.JCheckBox supplierCheckBox;
    private javax.swing.JComboBox supplierCombo;
    // End of variables declaration//GEN-END:variables
}
