/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vidulaPharma.view.pharmacist;

import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import java.awt.Frame;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import vidulaPharma.controller.CustomerOrderController;
import vidulaPharma.controller.DrugController;
import vidulaPharma.controller.PharmaNameController;
import vidulaPharma.controller.TradeNameController;
import vidulaPharma.model.CustomerOrder;
import vidulaPharma.model.Drug;
import vidulaPharma.model.PharamaName;
import vidulaPharma.model.TradeName;
import vidulaPharma.view.LoginDialog;

/**
 *
 * @author isuru
 */
public class PharamacistForm extends javax.swing.JFrame {

    private TradeNameController tradeNameController;
    private PharmaNameController pharmaNameController;
    private Drug drug;
    private String tradeName;
    private String genericName;
    private double total;
    private double price;
    private DefaultTableModel orderTableModel;
    private boolean isFirst;
    private ArrayList<String> dNameIdArray;
    private ArrayList<String> dNameArray;
    private ArrayList<Drug> orderedDrugsList;
    private static PharamacistForm pForm;
    private TestTable testTable;
    ImageIcon imageIco;
    private Drug drugItem;

    /**
     * Creates new form PharamacistForm
     */
    public PharamacistForm() {
        initComponents();
        setExtendedState(Frame.MAXIMIZED_BOTH);
//        buttonGroup.add(brandRadioButton);
        imageIco = new ImageIcon("../images/pharmacy.png");
        try {
            PharamacistForm.this.setIconImage(ImageIO.read(new File("images/pharmacy.png")));
        } catch (IOException ex) {
            Logger.getLogger(PharamacistForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.tradeNameController = new TradeNameController();
        this.pharmaNameController = new PharmaNameController();
        total = 0.0;
        price = 0.0;
        //orderTableModel = (DefaultTableModel) orderTable.getModel();
        isFirst = true;
        dNameIdArray = new ArrayList<>();
        dNameArray = new ArrayList<>();
        setDateTime();
        timerLabel2.setText(new SimpleDateFormat("EEE d - MM - yyyy").format(new Date()));
        pForm = PharamacistForm.this;
        testTable = new TestTable(pForm, false, pForm);
        orderedDrugsList = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        searchText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugXList = new javax.swing.JList();
        genericRadioButton = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        priceText = new javax.swing.JTextField();
        genericText = new javax.swing.JTextField();
        brandText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        expireText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        doseText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        typeText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addToButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        genericList = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        timerLabel2 = new javax.swing.JLabel();
        timeLabel2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewButton = new javax.swing.JButton();
        totalLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        searchMenuItem = new javax.swing.JMenuItem();
        searchByGMenuItem = new javax.swing.JMenuItem();
        printMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vidula Pharma");
        setBackground(new java.awt.Color(26, 23, 21));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(33, 33, 33));

        searchPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        searchText.setText("Search");
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTextKeyTyped(evt);
            }
        });

        drugXList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                drugXListValueChanged(evt);
            }
        });
        drugXList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                drugXListKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                drugXListKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(drugXList);

        genericRadioButton.setText("Search By Generic Name");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(searchText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genericRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genericRadioButton)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Drug Details"));

        jLabel3.setText("Generic Name");

        jLabel1.setText("Brand Name ");

        jLabel6.setText("Unit Price");

        jLabel5.setText("Expire Date");

        jLabel4.setText("Dose");

        jLabel7.setText("Type");

        addToButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidulaPharma/images/cart .resized.png"))); // NOI18N
        addToButton.setText("              Add to Order");
        addToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brandText)
                    .addComponent(genericText)
                    .addComponent(doseText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeText)
                    .addComponent(priceText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expireText))
                .addContainerGap())
            .addComponent(addToButton, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(genericText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(typeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(doseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(expireText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidulaPharma/images/print.resized.png"))); // NOI18N
        printButton.setText("OK");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidulaPharma/images/close.resized.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        genericList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                genericListValueChanged(evt);
            }
        });
        genericList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                genericListKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(genericList);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        timerLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        timerLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerLabel2.setText("Date");

        timeLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        timeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel2.setText("Time");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vidula Pharma");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(timerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        viewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidulaPharma/images/view.resized.png"))); // NOI18N
        viewButton.setText("View Order");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        totalLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        totalLabel2.setText("Value");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel12.setText("Total    :");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setText("File");

        searchMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        searchMenuItem.setText("Search");
        searchMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(searchMenuItem);

        searchByGMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        searchByGMenuItem.setText("Search By Generic");
        searchByGMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByGMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(searchByGMenuItem);

        printMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        printMenuItem.setText("Print");
        printMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(printMenuItem);

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        quitMenuItem.setText("Quit");
        quitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(quitMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(searchPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelButton)
                            .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:

        System.out.println(evt.getModifiers());

        if (genericRadioButton.isSelected()) {
            DefaultListModel<PharamaName> pNameList = new DefaultListModel<>();
            try {
                ArrayList<PharamaName> searchPharamaName = (ArrayList<PharamaName>) PharmaNameController.searchPharamaName(searchText.getText(), "name");
                for (PharamaName pName : searchPharamaName) {
                    pNameList.addElement(pName);
                }
            } catch (SQLException ex) {
                Logger.getLogger(PharamacistForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            drugXList.setModel(pNameList);
            if (!pNameList.isEmpty()) {
                drugXList.requestFocus();
                drugXList.setSelectedIndex(0);
            }
        } else {
            ArrayList<TradeName> tradeNameList = new ArrayList<>();
            ArrayList<Drug> drugList = new ArrayList<>();
            DefaultListModel listModel = new DefaultListModel();
            try {
                ResultSet res = DrugController.pharmacistSearch(searchText.getText(), "trade_name");
                while (res.next()) {
                    drug = new Drug(res.getString("drug_id"), res.getString("drug_name_id"), res.getString("drug_type"), res.getInt("drug_dose"), res.getDouble("drug_unit_price"), res.getString("drug_expire_date"), res.getString("drug_qty"), res.getBoolean("availability"));
                    drugList.add(drug);
                    TradeName tName = new TradeName(res.getString("trade_id"), res.getString("pharma_id"), res.getString("trade_name"));
                    tradeNameList.add(tName);
                }
            } catch (SQLException ex) {
                Logger.getLogger(PharamacistForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            for (TradeName tName : tradeNameList) {
                System.out.println(tName.getTradeId() + "-" + tName + " post");
                listModel.addElement(tName);
            }
            drugXList.setModel(listModel);
            if (!listModel.isEmpty()) {
                drugXList.requestFocus();
                drugXList.setSelectedIndex(0);
            }

        }

    }//GEN-LAST:event_searchTextActionPerformed

    protected void refreshAll() {
        brandText.setText("");
        genericText.setText("");
        typeText.setText("");
        doseText.setText("");
        expireText.setText("");
        priceText.setText("");
        //orderTable.removeAll();
        isFirst = true;
        searchText.requestFocus();
//        orderTableModel.addRow(new Object[]{});
//        orderTableModel.addRow(new Object[]{"","","Total","0.0"});
    }
    private void drugXListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_drugXListValueChanged
        if (!genericRadioButton.isSelected()) {
            if (drugXList.getSelectedIndex() != -1) {
                try {
                    TradeName tradeName = (TradeName) drugXList.getSelectedValue();
                    String pharmaName = PharmaNameController.searchPharmaId(tradeName.getPharmaId());
                    drugItem = DrugController.searchDrugByTradeName(tradeName.getTradeId());
                    System.out.println(drugItem.toString());
                    setDetails(drugItem, tradeName.toString(), pharmaName);
                } catch (SQLException ex) {
                    Logger.getLogger(PharamacistForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            if (drugXList.getSelectedIndex() != -1) {
                PharamaName pName = (PharamaName) drugXList.getSelectedValue();
                String pNameId = pName.getPharmaId();
                genericName = pName.getPharmaName();
                dNameArray.clear();
                try {
                    ResultSet results = DrugController.pharmacistSearchForPharmaName(pNameId);
                    while (results.next()) {
                        dNameIdArray.add(results.getString("drug_id"));
                        dNameArray.add(results.getString("trade_name"));
                    }
                    setDrugNames(dNameArray);
                } catch (SQLException ex) {
                    Logger.getLogger(PharamacistForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_drugXListValueChanged

    protected void setDrugNames(ArrayList<String> dNameList) {
        int index = 0;
        DefaultListModel<String> dNameListModel = new DefaultListModel<>();
        while (!dNameList.isEmpty() && index < dNameList.size()) {
            dNameListModel.addElement(dNameList.get(index++));
        }
        genericList.setModel(dNameListModel);
    }
    private void addToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToButtonActionPerformed
        // TODO add your handling code here:
        String drugName = brandText.getText();
        String qty = JOptionPane.showInputDialog(PharamacistForm.this, "Enter the amount :", "Amount", JOptionPane.QUESTION_MESSAGE);
        String unitPrice = priceText.getText();
        //setTable(drugName, qty, unitPrice);
        total = testTable.setTable(drugName, qty, unitPrice);
        testTable.setVisible(true);
        totalLabel2.setText(Double.toString(total));
        refreshAll();
        searchText.requestFocus();

        drugItem.setQtyOnHand(Integer.toString(Integer.parseInt(drugItem.getQtyOnHand()) - Integer.parseInt(qty)));
        orderedDrugsList.add(drugItem);
    }//GEN-LAST:event_addToButtonActionPerformed

    protected void setTable(String drugName, String qty, String unitPrice) {
        price = Integer.parseInt(qty) * Double.parseDouble(unitPrice);
        total = total + price;


        orderTableModel.removeRow(orderTableModel.getRowCount() - 1);
        orderTableModel.removeRow(orderTableModel.getRowCount() - 1);
        orderTableModel.addRow(new Object[]{drugName, qty, unitPrice, price});
        orderTableModel.addRow(new Object[]{});
        orderTableModel.addRow(new Object[]{"", "", "Total", total});
    }
    private void drugXListKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drugXListKeyTyped
        // TODO add your handling code here:  
    }//GEN-LAST:event_drugXListKeyTyped

    private void drugXListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drugXListKeyPressed
        if (!genericRadioButton.isSelected()) {
            //set Focus to button
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                addToButton.requestFocus();
            }
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                genericList.requestFocus();
                genericList.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_drugXListKeyPressed

    private void searchTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextKeyPressed

    private void searchTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyTyped
        // TODO add your handling code here:
        if (isFirst) {
            searchText.setText("");
            isFirst = false;
        }
    }//GEN-LAST:event_searchTextKeyTyped

    private void searchMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMenuItemActionPerformed
        // TODO add your handling code here:
        searchText.requestFocus();
        genericRadioButton.setSelected(false);
        genericList.setEnabled(false);
        isFirst = true;
    }//GEN-LAST:event_searchMenuItemActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            boolean isSuccess = DrugController.updateQty(orderedDrugsList);
            if(isSuccess){
                CustomerOrder cusOrder = new CustomerOrder(CustomerOrderController.getNewId(), new SimpleDateFormat("dd/MM/yyyy").format(new Date()), total, "E001");
                CustomerOrderController.addCustomerOrder(cusOrder);
            }

        } catch (SQLException ex) {
            Logger.getLogger(PharamacistForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_printButtonActionPerformed

    private void setDateTime() {
        javax.swing.Timer timer;
        timer = new javax.swing.Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timeLabel2.setText(new SimpleDateFormat("hh:mm:ss").format(new Date())); //To change body of generated methods, choose Tools | Templates.
            }
        });
        timer.start();
    }
    private void printMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printMenuItemActionPerformed
        printButtonActionPerformed(evt);
    }//GEN-LAST:event_printMenuItemActionPerformed

    private void genericListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_genericListValueChanged

        if (genericList.getSelectedIndex() != -1) {
            String drugId = dNameIdArray.get(genericList.getSelectedIndex());
            try {
                drugItem = DrugController.getDrug(drugId);
                String dName = (String) genericList.getSelectedValue();
                System.out.println("genericListValueChanged : item - " + dName);
                setDetails(drugItem, dName, genericName);
            } catch (SQLException ex) {
                Logger.getLogger(PharamacistForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_genericListValueChanged

    private void quitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuItemActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_quitMenuItemActionPerformed

    private void genericListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genericListKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addToButton.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            drugXList.requestFocus();
            drugXList.setSelectedIndex(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_genericListKeyPressed

    private void searchByGMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByGMenuItemActionPerformed

        genericRadioButton.setSelected(true);
        genericList.setEnabled(true);
        searchText.setText("Search");
        searchText.requestFocus();
        refreshAll();// TODO add your handling code here:
    }//GEN-LAST:event_searchByGMenuItemActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        if (testTable != null) {
            testTable.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_viewButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    protected void setDetails(Drug drug, String tradeName, String genericName) {
        if (drug != null) {
            brandText.setText(tradeName);
            genericText.setText(genericName);
            typeText.setText(drug.getDrugType());
            doseText.setText(Integer.toString(drug.getDose()));
            expireText.setText(drug.getExpireDate());
            priceText.setText(Double.toString(drug.getUnitPrice()));
        }

    }

    private static PharamacistForm getInstance() {
        return pForm;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        final AcrylLookAndFeel alaf = new AcrylLookAndFeel();

        try {
            UIManager.setLookAndFeel(alaf);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PharamacistForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharamacistForm().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToButton;
    private javax.swing.JTextField brandText;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField doseText;
    private javax.swing.JList drugXList;
    private javax.swing.JTextField expireText;
    private javax.swing.JList genericList;
    private javax.swing.JCheckBox genericRadioButton;
    private javax.swing.JTextField genericText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField priceText;
    private javax.swing.JButton printButton;
    private javax.swing.JMenuItem printMenuItem;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JMenuItem searchByGMenuItem;
    private javax.swing.JMenuItem searchMenuItem;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchText;
    private javax.swing.JLabel timeLabel2;
    private javax.swing.JLabel timerLabel2;
    private javax.swing.JLabel totalLabel2;
    private javax.swing.JTextField typeText;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
